feat(cardinal): dynamic abi gen for transactions
Argus-Labs/world-engine pull request #194
Opened 2023-08-04 18:52 UTC by technicallyty

Closes: #XXX

## What is the purpose of the change

> Add a description of the overall background and high-level changes that this PR introduces

_(E.g.: This pull request improves documation of area A by adding ...._

## Brief Changelog

_(for example:)_

- _The metadata is stored in the blob store on job creation time as a persistent artifact_
- _Deployments RPC transmits only the blob storage reference_
- _Daemons retrieve the RPC data from the blob cache_

## Testing and Verifying

_(Please pick one of the following options)_

This change is a trivial rework/code cleanup without any test coverage.

_(or)_

This change is already covered by existing tests, such as _(please describe tests)_.

_(or)_

This change added tests and can be verified as follows:

_(example:)_

- _Added unit test that validates ..._
- _Added integration tests for end-to-end deployment with ..._
- _Extended integration test for ..._
- _Manually verified the change by ..._

2023-08-08 18:48 UTC, namrapatel approved these changes

2023-08-08 18:48 UTC, namrapatel approved these changes

2023-08-09 17:33 UTC, jerargus requested changes

2023-08-09 17:33 UTC, jerargus commented on cardinal/ecs/persona.go
> +var CreatePersonaTx = NewTransactionType[CreatePersonaTransaction](
I recently made a change to NewTransactionType to take in two generic arguments.

2023-08-10 01:03 UTC, technicallyty commented on cardinal/ecs/tests/transaction_test.go
> +	assert.ErrorContains(t, err, "EVM type is not set")
ah, forgot to update that after i made the typed error. [test: change test to use ErrorIs](https://github.com/Argus-Labs/world-engine/pull/194/commits/c073251698137f9e29b7d33414dccdcf5933b9f8) fixed here

2023-08-10 21:03 UTC, jerargus approved these changes

2023-08-10 21:04 UTC, merged