Brian/car 111/remove hoststr default port
Argus-Labs/world-engine pull request #207
Opened 2023-08-16 21:26 UTC by pyrofolium

Closes: #CAR-111

## What is the purpose of the change
Change function signature of Serve in server.go to remove host and port

> Add a description of the overall background and high-level changes that this PR introduces

Changes the function signature of Serve to be simplified. However this involves the Serve to default to a specific port or there will be an error. I used 4040 because it's what was used in the unit test. 

## Brief Changelog

- removes entry for host as it's not needed at all, go libraries have a default
- removes port as a parameter and sets it as a property of handler. 
- If port is never set, Server runs with a default of 4040
- Added WithPort("some port string") as an "Option" for the test factory. Users can use this to set a port if they don't want the default. Though this pattern is a little complex, tbh. We can discuss. 
- Changed unit tests to work with new changes. 

## Testing and Verifying

Adjusted unit tests to account for new changes. 
Ran tests to see it still works.

2023-08-16 23:19 UTC, namrapatel reviewed
@jerargus Should we make the change in the submoduled starter-game-template too? Not sure if thats the practice we're going for now

2023-08-16 23:41 UTC, jerargus commented
> @jerargus Should we make the change in the submoduled starter-game-template too? Not sure if thats the practice we're going for now

Once this is merged, the next time the starter-game-template increases its cardinal version, it will get this code and the call to txh.Serve() will fail. So whoever ends up doing that version increase will have to fix it (i suspect it will be me in the next few days). There's nothing to do right away.

2023-08-16 23:42 UTC, jerargus approved these changes

2023-08-16 23:47 UTC, smsunarto requested changes
I think we should allow changing the port using `CARDINAL_PORT` environment variable.

2023-08-17 02:54 UTC, namrapatel approved these changes

2023-08-17 16:53 UTC, technicallyty approved these changes
lgtm, just a few minor things

2023-08-17 16:53 UTC, technicallyty commented on cardinal/server/server_test.go
> +	assert.NilError(t, world.RegisterTransactions(alphaTx, betaTx, gammaTx))
```suggestion
	assert.NilError(t, world.RegisterTransactions(alphaTx))
```

will be fine with one tx registered

2023-08-17 16:53 UTC, technicallyty commented on cardinal/server/server.go
> +func (t *Handler) Serve() {
```suggestion

// Serve sets up the endpoints passed in by the user, as well as a special "/list" endpoint, that informs consumers
// what endpoints the user set up in the Handler. Then, it serves the application, blocking the main thread.
// Please us `go txh.Serve()` if you do not want to block execution after calling this function.
func (t *Handler) Serve() {
```

2023-08-17 18:23 UTC, pyrofolium commented
> I think we should allow changing the port using `CARDINAL_PORT` environment variable.

@smsunarto made those changes. Let me know if it works.

2023-08-19 04:51 UTC, smsunarto approved these changes
lgtm

2023-08-19 04:51 UTC, merged