Tyler/e2e game
Argus-Labs/world-engine pull request #226
Opened 2023-08-25 03:43 UTC by technicallyty

Closes: #XXX

## What is the purpose of the change

> Add a description of the overall background and high-level changes that this PR introduces

_(E.g.: This pull request improves documation of area A by adding ...._

## Brief Changelog

_(for example:)_

- _The metadata is stored in the blob store on job creation time as a persistent artifact_
- _Deployments RPC transmits only the blob storage reference_
- _Daemons retrieve the RPC data from the blob cache_

## Testing and Verifying

_(Please pick one of the following options)_

This change is a trivial rework/code cleanup without any test coverage.

_(or)_

This change is already covered by existing tests, such as _(please describe tests)_.

_(or)_

This change added tests and can be verified as follows:

_(example:)_

- _Added unit test that validates ..._
- _Added integration tests for end-to-end deployment with ..._
- _Extended integration test for ..._
- _Manually verified the change by ..._

2023-09-28 16:43 UTC, heronimus commented on chain/scripts/start-rollup.sh
```suggestion

# Cosmos SDK gRPC listener
sed -i'.bak' 's#"localhost:9090"#"0.0.0.0:9090"#g' /root/.world/config/app.toml
# Cosmos SDK API server listener
sed -i'.bak' 's#"localhost:1317"#"0.0.0.0:1317"#g' /root/.world/config/app.toml

```

2023-10-05 01:34 UTC, heronimus commented on chain/scripts/start-rollup.sh
> +sed -i'.bak' 's#"localhost:1317"#"0.0.0.0:1317"#g' /root/.world/config/app.toml
I put an extra double quote here before; just realized it when I deployed it previously.
```suggestion
sed -i'.bak' 's#localhost:1317#0.0.0.0:1317#g' /root/.world/config/app.toml
```

2023-10-26 16:54 UTC, pyrofolium requested changes
I feel the infra for e2e tests here are redundant to `mage test` in starter-game-template. 
It's unfortunate no one noticed that there was a parallel effort here. 

I think all the tests need to be combined into one repo (this one). And all tests run with one command. So all regular world-engine tests, all starter-game-template tests, and all of the new e2e you created should be run here. 

And it should be either mage or make, I don't think we should have both. I'm not too deeply familiar with either mage or make but given that are whole ecosystem is golang anyway I would prefer mage to keep things consistent and simpler (as I don't have to learn make)

I'm going to place this under "request changes" but if you want to punt this to another issue, lmk I can approve. I'd punt it too. But I feel this overall issue is something that must be done eventually so we should talk about it a little get some consensus on the overall direction here. 

As we talked about earlier there were failing tests on the starter-game-template side so getting these combined improves overall robustness


These are my thoughts on the matter let me know yours.

2023-10-26 17:18 UTC, technicallyty commented
> I feel the infra for e2e tests here are redundant to `mage test` in starter-game-template. It's unfortunate no one noticed that there was a parallel effort here.
> 
> I think all the tests need to be combined into one repo (this one). And all tests run with one command. So all regular world-engine tests, all starter-game-template tests, and all of the new e2e you created should be run here.
> 
> And it should be either mage or make, I don't think we should have both. I'm not too deeply familiar with either mage or make but given that are whole ecosystem is golang anyway I would prefer mage to keep things consistent and simpler (as I don't have to learn make)
> 
> I'm going to place this under "request changes" but if you want to punt this to another issue, lmk I can approve. I'd punt it too. But I feel this overall issue is something that must be done eventually so we should talk about it a little get some consensus on the overall direction here.
> 
> As we talked about earlier there were failing tests on the starter-game-template side so getting these combined improves overall robustness
> 
> These are my thoughts on the matter let me know yours.

this e2e test is for chain related testing. it is different than the one in starter game template

2023-10-26 17:22 UTC, pyrofolium commented
I recall everyone agreeing on using mage? 

Either way moving 

> > I feel the infra for e2e tests here are redundant to `mage test` in starter-game-template. It's unfortunate no one noticed that there was a parallel effort here.
> > I think all the tests need to be combined into one repo (this one). And all tests run with one command. So all regular world-engine tests, all starter-game-template tests, and all of the new e2e you created should be run here.
> > And it should be either mage or make, I don't think we should have both. I'm not too deeply familiar with either mage or make but given that are whole ecosystem is golang anyway I would prefer mage to keep things consistent and simpler (as I don't have to learn make)
> > I'm going to place this under "request changes" but if you want to punt this to another issue, lmk I can approve. I'd punt it too. But I feel this overall issue is something that must be done eventually so we should talk about it a little get some consensus on the overall direction here.
> > As we talked about earlier there were failing tests on the starter-game-template side so getting these combined improves overall robustness
> > These are my thoughts on the matter let me know yours.
> 
> this e2e test is for chain related testing. it is different than the one in starter game template

As discussed these e2e tests are just for testing chain related stuff. For the future we need to combine all tests together.

2023-10-26 19:33 UTC, namrapatel approved these changes

2023-10-26 19:46 UTC, merged