change /query/http/endpoints to /endpoints
Argus-Labs/world-engine pull request #700
Opened 2024-03-21 12:27 UTC by zulkhair

Closes: WORLD-XXX

## Overview

> Description of the overall background and high-level changes that this PR introduces

## Brief Changelog

## Testing and Verifying

2024-03-21 12:27 UTC, zulkhair commented
* **#700** <a href="https://app.graphite.dev/github/pr/Argus-Labs/world-engine/700?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @zulkhair and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-03-21 18:50 UTC, technicallyty reviewed
theres another occurence of query/http/endpoints in `cardinal/server/handler/endpoints.go L24`

2024-03-21 18:54 UTC, smsunarto approved these changes
I think I would prefer to deprecate this and serve the swagger.json file instead. It serves a similar purpose and swagger would gives us more capabilities

2024-03-21 18:54 UTC, smsunarto requested changes
see above comments

2024-03-25 22:15 UTC, zulkhair commented
> I think I would prefer to deprecate this and serve the swagger.json file instead. It serves a similar purpose and swagger would gives us more capabilities

Updated
- Remove /endpoints
- Adjust nakama to get enpoint from /world

2024-03-26 04:57 UTC, smsunarto approved these changes
left optional nit, otherwise lgtm

2024-03-26 04:57 UTC, smsunarto commented on relay/nakama/main.go
> -	ListEndpoints             = "query/http/endpoints"
nit: we probably should rename it from `ListEndpoints` to `WorldEndpoint`

2024-03-26 10:02 UTC, merged