feat: add namespace to /world endpoint
Argus-Labs/world-engine pull request #701
Opened 2024-03-21 13:08 UTC by zulkhair

Closes: WORLD-XXX

## Overview

> Description of the overall background and high-level changes that this PR introduces

## Brief Changelog

## Testing and Verifying

2024-03-21 15:51 UTC, rmrt1n approved these changes

2024-03-21 18:48 UTC, technicallyty approved these changes
i think aesthetically, namespace would look better at the top of the JSON

2024-03-21 18:57 UTC, smsunarto requested changes
the queries URL are invalid. it should've start with /query not /tx

2024-03-21 19:06 UTC, zulkhair commented
> the queries URL are invalid. it should've start with /query not /tx

fixed

2024-03-22 21:52 UTC, smsunarto approved these changes

2024-03-23 05:12 UTC, merged