ci: markdown-lint
Argus-Labs/world-engine pull request #708
Opened 2024-03-25 08:59 UTC by heronimus

Closes: WORLD-983

## Overview

Add markdown linter 

## Brief Changelog

- https://github.com/marketplace/actions/markdown-lint

## Testing and Verifying

- CI passed

2024-03-25 18:52 UTC, smsunarto commented
Is this ready for review?

2024-03-25 19:15 UTC, heronimus commented
It's now ready, also with [world-cli](https://github.com/Argus-Labs/world-cli/pull/50) and [SGT](https://github.com/Argus-Labs/starter-game-template/pull/39)

2024-03-25 19:18 UTC, technicallyty approved these changes
nice

2024-03-25 19:18 UTC, smsunarto requested changes

2024-03-25 19:18 UTC, smsunarto commented on .github/workflows/lint-markdown.yml
> +on:
- Add .mdx linter (https://github.com/mdx-js/eslint-mdx)
- Only trigger when there are changes to `.md/.mdx` file

2024-03-25 19:56 UTC, smsunarto commented on .github/workflows/lint-markdown.yml
> +  md-lint:
convention for jobs name is `[workflow name]-[jobs name]` this should be `lint-md`.

Would appreciate if you can note this down so I don't have to nit/fix it everytime

2024-03-25 20:22 UTC, smsunarto commented
test

2024-03-28 11:22 UTC, heronimus commented
^^ PR is ready for re-review

2024-03-28 20:47 UTC, smsunarto commented on .eslintrc
> +  // lint code blocks true
```suggestion
```

2024-03-28 20:49 UTC, smsunarto approved these changes

2024-03-28 21:00 UTC, merged