refactor(cardinal). move message and query into cardinal.
Argus-Labs/world-engine pull request #754
Opened 2024-05-01 18:25 UTC by pyrofolium

Closes: WORLD-1110

Move query and message into cardinal. Very mechanical. 

There are some name changes too. Some things like `messages.NewManager` have been changed to `cardinal.NewMessageManager` where relevant.

2024-05-01 19:37 UTC, jerargus approved these changes

2024-05-02 20:50 UTC, smsunarto requested changes

2024-05-02 20:50 UTC, smsunarto commented on cardinal/message_manager.go
The managers needs to be thrown under an interface like my example (https://github.com/Argus-Labs/world-engine/pull/749/files#diff-490f654845fb6b98fad55dbdaf2a4cbe5920862f802ca6bc8c6c423ff1ce4753R27-R39, https://github.com/Argus-Labs/world-engine/pull/749/files#diff-a347e172c71021c8563a1e76f2c8814a8d97f2ae01991104af1475c56fe7d4c9R49) here so that users can't accidentally modify the manager struct fields that are now directly accessible. 

Also notice that the manager struct is now private to prevent people from directly accessing it.

2024-05-02 20:50 UTC, smsunarto commented on cardinal/world.go
> +	msgManager       *MessageManager
See my comment above w/r/t to interfaces

2024-05-02 20:50 UTC, smsunarto commented on cardinal/world.go
There are functions that currently route method calls to the manager, such as `GetComponentByName` and `GetMessageByName`, that could be removed since are using interface composition to provide that functionality directly to World. see example here: https://github.com/Argus-Labs/world-engine/pull/749/files#diff-a347e172c71021c8563a1e76f2c8814a8d97f2ae01991104af1475c56fe7d4c9

2024-05-03 18:29 UTC, pyrofolium commented on cardinal/world.go
I'll create another ticket for the other managers too.

2024-05-03 18:31 UTC, smsunarto commented on cardinal/world.go
my bad, yeah i meant the message and query [](edited-with-Axolo)

2024-05-03 21:49 UTC, pyrofolium commented on cardinal/world.go
There's problems doing this for MessageManager due to the fact that World needs to implement the Provider interface in router.go. I'm going to leave it out for now and resolve. lmk if you want me to try to attack this or if you have any ideas on it.

2024-05-07 20:01 UTC, smsunarto commented on cardinal/cardinal_test.go
> -type Health struct {
If there is already a component with the same name in the package then just reuse it

2024-05-07 20:03 UTC, smsunarto commented on cardinal/message_manager.go
> +type MessageManagerImpl struct {
this struct doesn't need to be public. just follow the naming convention from the system.go (https://github.com/Argus-Labs/world-engine/blob/main/cardinal/system.go)

2024-05-07 20:09 UTC, smsunarto requested changes

2024-05-07 20:09 UTC, smsunarto commented on cardinal/message_manager.go
> +func NewMessageManager() MessageManager {
also doesnt need to be public

2024-05-07 20:09 UTC, smsunarto commented on cardinal/query_manager.go
same comments as the message manager

2024-05-07 20:09 UTC, smsunarto commented on cardinal/world.go
> +	msgManager       MessageManager
This should just be `MessageManager` similar to SystemManager. Move this and the QueryManager up to below the SystemManager

2024-05-07 21:24 UTC, smsunarto approved these changes

2024-05-07 21:25 UTC, merged