feat: new custom auth/link handler using argus id
Argus-Labs/world-engine pull request #815
Opened 2024-11-21 15:46 UTC by rmrt1n

Closes: WORLD-1254

## Overview

This PR adds the handlers for custom authentication and linking using [Argus ID](https://app.campsite.com/argus-labs/notes/r3v47d5ui0vw). ATM, only us (Argus Labs) can use this custom authentication as it requires a symmetric JWT secret key to verify the JWTs issued by Supabase. Once [asymmetric JWTs](https://github.com/orgs/supabase/discussions/29289) are rolled out, third parties should be able to use it too.

There's a slight change from the original design document. Instead of using the JWTs as the IDs for `AuthenticateCustom`, we're using the SHA256 hash of the JWT as the ID and including the JWT in the request variables. This change is made because `AuthenticateCustom` has an ID max length limit of 128 characters, which isn't long enough to contain the entirety of the JWT.

## Brief Changelog

- Add new custom auth type `'argus'` and the handlers for authentication and linking
- Add logic for verifying and parsing the JWT
- Add trace information to both Argus ID and SIWE handlers

## Testing and Verifying

Added unit tests to validate the JWT verifying and parsing logic.

2024-11-21 15:46 UTC, rmrt1n commented
* **#815** <a href="https://app.graphite.dev/github/pr/Argus-Labs/world-engine/815?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/Argus-Labs/world-engine/815?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-11-21 16:49 UTC, rmrt1n commented on relay/nakama/auth/argus_id.go
> +	}
this is fine

2024-11-21 17:02 UTC, rmrt1n commented on relay/nakama/auth/custom.go
> +	}
it's fine

2024-11-21 17:04 UTC, rmrt1n commented on relay/nakama/auth/custom.go
> +	ctx, span := otel.Tracer("nakama.auth").Start(ctx, "AuthenticateCustom",
this should be covered by errors returned in `validateAndParseJWT`

2024-11-21 17:07 UTC, rmrt1n commented on relay/nakama/auth/argus_id.go
> +	}
I'm pretty sure its set to empty map by default

2024-11-21 17:32 UTC, rmrt1n commented on relay/nakama/auth/argus_id_test.go
> +}
it's fine

2024-11-21 17:32 UTC, rmrt1n commented on relay/nakama/auth/custom.go
> +}
it's not called concurrently

2024-12-04 23:12 UTC, smsunarto requested changes
just some nits, otherwise lgtm

2024-12-09 16:50 UTC, rmrt1n commented on relay/nakama/auth/argus_id.go
> +type SupabaseClaims struct {
Found out that `claims, ok := token.Claims.(*SupabaseClaims)` isn't a strict type coersion, and will return ok for claims that look nothing like the desired type. This means we still have to manually check the existence of every field that we need.

I ended up removing all of fields that are not used, which leaves:

```go
type SupabaseClaims struct {
  jwt.StandardClaims
  UserMetaData map[string]interface{} `json:"user_metadata"`
}
```
wdyt?

2024-12-11 01:16 UTC, smsunarto commented on relay/nakama/auth/argus_id.go
> +type SupabaseClaims struct {
lgtm

2024-12-11 01:18 UTC, smsunarto commented on relay/nakama/auth/argus_id.go
> +	span.AddEvent("Validating and Parsing JWT")
@rmrt1n I don't think this is resolved yet.

2024-12-11 01:20 UTC, smsunarto requested changes

2024-12-11 01:20 UTC, smsunarto commented on relay/nakama/auth/siwe.go
> +	span trace.Span,
you don't need to be dependency injecting the span around, you can use SpanFromContext (see https://opentelemetry.io/docs/languages/go/instrumentation/#get-the-current-span)

2024-12-11 15:50 UTC, rmrt1n commented on relay/nakama/auth/argus_id.go
> +	span.AddEvent("Validating and Parsing JWT")
I did though, [here](https://github.com/Argus-Labs/world-engine/pull/815/files#diff-9d382e42476b01f2cc3dfa8e13d43136df75cfa689c56f6a4ca30d32ef6dd57eR44).

2024-12-11 21:53 UTC, smsunarto approved these changes
Approving with comments -- there are some that is still using OTel trace event that should've been subspan. Once that's fixed feel free to merge

2024-12-11 21:53 UTC, smsunarto commented on relay/nakama/auth/custom.go
> +		span.AddEvent("Handling custom auth with Argus ID")
This should also be a subspan instead of event

2024-12-11 21:53 UTC, smsunarto commented on relay/nakama/auth/custom.go
> +		span.AddEvent("Handling custom auth with SIWE")
This should also be a subspan instead of event

2024-12-12 18:09 UTC, merged